name: Gem CI

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-ruby@v1
      - name: Install Gems
        run: bundle install
      - name: Run Tests
        run: bundle exec rake spec
  build:
    name: Build Gem
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-ruby@v1
      - name: Build Gem
        run: gem build *.gemspec
      - name: Upload built gem
        uses: actions/upload-artifact@v2-preview
        with:
          name: ksp-ci.gem
          path: "*.gem"
  publish:
    name: Publish to Github Packages
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/setup-ruby@v1
    - name: Setup publishing credentials
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
    - name: Download built gem
      uses: actions/download-artifact@v1
      with:
        name: ksp-ci.gem
        path: ksp-ci.gem
    - name: Publish
      run: gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} ksp-ci.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.GPR_AUTH_TOKEN}}
        OWNER: username
