name: Gem CI

on: [push, pull_request]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: ruby/setup-ruby@v1
      - name: Install Gems
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-ruby@v1
      - name: Install Gems
        run: bundle install
      - name: Run Tests
        run: bundle exec rake spec
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: ruby/setup-ruby@v1
      - name: Build Gem
        run: gem build *.gemspec
      - name: Upload built gem
        uses: actions/upload-artifact@v2
        with:
          name: built-gem
          path: "*.gem"
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [rubocop, test, build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: ruby/setup-ruby@v1
    - name: Setup publishing credentials
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p "${HOME}/.gem"
        touch "${HOME}/.gem/credentials"
        chmod 0600 "${HOME}/.gem/credentials"
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > "${HOME}/.gem/credentials"
    - name: Set repo owner env
      run: echo "::set-env name=REPO_OWNER::$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 1)"
    - name: Download built gem
      uses: actions/download-artifact@v2
      with:
        name: built-gem
    - name: Publish
      run: gem push --KEY github --host https://rubygems.pkg.github.com/${REPO_OWNER} built-gem/*.gem
